- build: examples/simple
  photon: [latest]
  p1: [latest]
  electron: [1.0.0, 1.1.0, 1.2.1, 1.3.1, 1.4.2]
  argon: [0.9.0, latest]
  boron: [latest]
  xenon: [latest]
- build: examples/test1m
  photon: [latest]
  electron: [latest]
  argon: [latest]
